name: "LintPrTitle"

on:
  push: {}

jobs:
  WithPrsCreated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: release_please
        id: release_please
        run: |
          echo "prs_created='true'" >> $GITHUB_OUTPUT
          echo "releases_created='false'" >> $GITHUB_OUTPUT
          echo "release_version=''" >> $GITHUB_OUTPUT

      - name: Git
        id: version
        run: |
          echo "${{ toJSON(steps.release_please.outputs) }}" | yq -o=json -I=0 .

          .github/cmds/get_release_version.sh \
            $(echo "${{ toJSON(steps.release_please.outputs) }}" | yq -o=json -I=0 . ) \
            "$GITHUB_OUTPUT"

      - name: Print
        run: |
          echo "${{ toJSON(steps.version.outputs) }}" | yq -o=json -I=0 .

  WithReleaseCreated:
    runs-on: ubuntu-latest
    needs: WithPrsCreated
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: release_please
        id: release_please
        run: |
          echo "prs_created=false" >> $GITHUB_OUTPUT
          echo "releases_created=true" >> $GITHUB_OUTPUT
          echo "release_version='0.1.1'" >> $GITHUB_OUTPUT

      - name: Git
        id: version
        run: |
          echo "${{ toJSON(steps.release_please.outputs) }}" | yq -o=json -I=0 .

          .github/cmds/get_release_version.sh \
            $(echo "${{ toJSON(steps.release_please.outputs) }}" | yq -o=json -I=0 .) \
            "$GITHUB_OUTPUT"

      - name: Print
        run: |
          echo "${{ toJSON(steps.version.outputs) }}" | yq -o=json -I=0 .
