site_name: Beancount Importer Rules
site_url: https://zenobi-us.github.io/beancount-importer-rules
repo_url: https://github.com/zenobi-us/beancount-importer-rules
repo_name: GitHub
edit_uri: ""

watch:
  - docs/
  - mkdocs.yml
  - beancount_importer_rules/

theme:
  name: "material"

  custom_dir: docs/overrides

  font:
    code: Roboto Mono
    text: Roboto Slab

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline

        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  features:
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.keys

plugins:
  - social
  - search
  - tags
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: "latest"
      version_selector: true
      css_dir: css
      javascript_dir: js

extra:
  version:
    provider: mike
