#!/usr/bin/env bash
# mise description="ouputs the version and track of the release"

payload="${1:-"{\"prs_created\": true, \"releases_created\": false, \"release_version\": \"\"}"}"
output="${2:-/dev/tty}"

prs_created=$(echo "${payload}" | jq -r '.prs_created')
releases_created=$(echo "${payload}" | jq -r '.releases_created')
release_version=$(echo "${payload}" | jq -r '.release_version')

if [ "${prs_created}" = "true" ]; then
    # https://packaging.python.org/en/latest/discussions/versioning/#local-version-identifiers
    # https://discuss.python.org/t/pip-pre-and-beta-dev-versions/9665
    # https://stackoverflow.com/a/24293364/454615

    tag=$(git describe --tags --abbrev=0)
    commits_since_last_tag=$(git log "$tag"..HEAD --oneline | wc -l)
    # strip v from tag
    last_tag=${tag#v}
    version="${last_tag}.dev${commits_since_last_tag}"

    echo "Version=${version}" >>"$output"
    echo "Track=dev" >>"$output"
fi

if [ "${releases_created}" = "true" ]; then
    echo "Version=${release_version}" >>"$output"
    echo "Track=stable" >>"$output"
fi
