#!/usr/bin/env bash
# mise description="ouputs the version and track of the release"

payload="${1:-"{\"prs_created\": true, \"releases_created\": false, \"release_version\": \"\"}"}"
output="${2:-/dev/tty}"

echo "Payload: ${payload}"

prs_created=$(echo "${payload}" | jq -r '.prs_created')
releases_created=$(echo "${payload}" | jq -r '.releases_created')
release_version=$(echo "${payload}" | jq -r '.release_version')

if [ "${prs_created}" = "true" ]; then
    # https://packaging.python.org/en/latest/discussions/versioning/#local-version-identifiers
    # https://discuss.python.org/t/pip-pre-and-beta-dev-versions/9665
    # https://stackoverflow.com/a/24293364/454615
    echo "Version=$(mise run compute-dev-version)" >>"$output"
    echo "Track=dev" >>"$output"
fi

if [ "${releases_created}" = "true" ]; then
    echo "Version=${release_version}" >>"$output"
    echo "Track=stable" >>"$output"
fi
