#!/usr/bin/env bash
# mise description="Compute the development version"

tag=$(git describe --tags --abbrev=0)

commits_since_last_tag=$(git log "$tag"..HEAD --oneline | wc -l)

# strip v from tag
last_tag=${tag#v}

version="${last_tag}.dev${commits_since_last_tag}"

echo "${version}"
