#!/usr/bin/env bash
# mise description="Build the documentation"
# mise sources=["mkdocs.yml", "docs/**/*.md", "beancount_importer_rules/**/*.py"]

echo ""
echo "🍜 Building documentation"
echo ""

pdm run mkdocs build

echo ""
echo "👍 Done"
echo ""
