#!/usr/bin/env bash
# mise description="Build the documentation"
# mise sources=["mkdocs.yml", "docs/**/*.md", "beancount_importer_rules/**/*.py"]

echo ""
echo "🍜 Deploying documentation [DEV]"
echo ""

mise run secrets-scan
mise run lint
mise run docs-build

tag=$(git describe --tags --abbrev=0)
commits_since_last_tag=$(git log "$tag"..HEAD --oneline | wc -l)
# strip v from tag
last_tag=${tag#v}
version="${last_tag}.dev${commits_since_last_tag}"

mise run docs-publish "${version}" "dev"

echo ""
echo "👍 Done"
echo ""
