#!/usr/bin/env bash
# mise description="Scans the project for secrets"
# mise sources=["beancount_importer_rules/**/*.py", "tests/**/*", ".github/**/*", ".mise/**/*", "docs/**/*", ".vscode/**/*" ]

echo ""
echo "🍜 Scanning for secrets"
echo ""

pdm run detect-secrets scan \
    --baseline \
    --exclude-files ".secrets.baseline" \
    --exclude-files ".venv/.*" >.secrets.baseline

echo ""
echo "👍 Done"
echo ""
