name: Pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the master branch
permissions:
  actions: read
  contents: read

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

      - uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd # v2.0.6
        with:
          version: 2024.8.12 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: true # [default: true] cache mise using GitHub's cache
          log_level: debug # [default: info] log level
          experimental: true

      - name: Install Python Packages
        uses: ./.github/actions/setup-dependencies

      - name: lint
        run: |
          mise run test:lint
          mise run test:types
          mise run test:test

      - name: Run tests
        shell: bash
        run: |
          mise run test:unit md_report.md
          echo "REPORT_FILE=md_report.md" >> "$GITHUB_ENV"

          mise run test:integration

      - name: Output reports to the job summary when tests fail
        if: failure()
        shell: bash
        run: |
          if [ -f "$REPORT_FILE" ]; then
            echo "<details><summary>Failed Test Report</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Compute Version
        id: preview-version
        run: |
          mise run compute-release-version \
            '{"prs_created": false, "is_pr_release": true, "releases_created": false, "release_version": null}' \
            "$GITHUB_OUTPUT"

      - name: Test Build and Publish
        run: |
          pdm version ${{ steps.preview-version.outputs.release_version }}
          # test build and publishing to testpypi
          mise run publish testpypi

      - name: docs
        run: mise run docs:build
